AuthorizationAndAuthentication/Controllers/AboutUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AuthorizationAndAuthentication.Controllers
{
    public class AboutUsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AuthorizationAndAuthentication/Controllers/AccountController.cs
using System.Threading.Tasks;
using AuthorizationAndAuthentication.ViewModel;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AuthorizationAndAuthentication.Controllers
{
    public class AccountController : Controller
    {
        private UserManager<IdentityUser> _userManager;
        private SignInManager<IdentityUser> _signInManager;

        public AccountController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel registerViewModel)
        {
            IdentityUser user = new IdentityUser()
            {
                UserName = registerViewModel.UserName,
                Email = registerViewModel.Email
            };

            var result = await _userManager.CreateAsync(user, registerViewModel.Password);
            var confirmation = await _userManager.GenerateEmailConfirmationTokenAsync(user);

            if (result.Succeeded)
            {
                return RedirectToAction("Login", "Account");
            }

            return View();
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Logout()   
        {
            await _signInManager.SignOutAsync();
            //return View();
            return RedirectToAction("Login", "Account");
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel loginViewModel)
        {
            var returnUrl = HttpContext.Request.Query["page"].ToString();

            var result = await _signInManager.PasswordSignInAsync(loginViewModel.Username, loginViewModel.Password,
                loginViewModel.RememberMe, true);

            if (result.Succeeded && !string.IsNullOrEmpty(returnUrl))
            {
                return RedirectToRoute(returnUrl);
            }

            if (result.Succeeded && string.IsNullOrEmpty(returnUrl))
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }
    }
}

AuthorizationAndAuthentication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AuthorizationAndAuthentication.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AuthorizationAndAuthentication/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AuthorizationAndAuthentication.Controllers
{
    [Authorize]
    public class StudentsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AuthorizationAndAuthentication/Views/AboutUs/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers


<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
</body>
</html>

AuthorizationAndAuthentication/Views/Home/Index.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
<h2>This is home Page</h2>
</body>
</html>

AuthorizationAndAuthentication/Views/Shared/_Layout.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_Layout</title>
</head>
<body>
    <header>
        <a asp-controller="Home" asp-action="Index">Home</a>
        <a asp-controller="AboutUs" asp-action="Index">About Us</a>
        @if (User.Identity.IsAuthenticated)
        {
            <a asp-controller="Students" asp-action="Index">Students</a>
        }

        @if (!User.Identity.IsAuthenticated)
        {
            <a asp-controller="Account" asp-action="Login">Sign in</a> 
            <a asp-controller="Account" asp-action="Register">Register</a>
        
        }
        else
        {
            <a asp-controller="Account" asp-action="Logout">Sign out</a><br />
        }

        @if (User.Identity.IsAuthenticated)
        {
            <h1>
                Welcome Mr. @User.Identity.Name
            </h1>
        }
    </header>
    <section>@RenderBody()</section>
    <footer>westlabels.com</footer>
</body>
</html>

AuthorizationAndAuthentication/Views/Students/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
</body>
</html>